apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-web-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/People257/k8s-learn
    targetRevision: master
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true